### ISSUE TITLE
Introduce `DirectedGraph`

### ISSUE THREAD

**Issue by qasim** [Vijay-Siva/Flows#2]
From docs:

> To create a directed graph, pass in true into the constructor.

Instead of passing `true` in the constructor, we could introduce a new class that extends `Graph`:

```js
class DirectedGraph extends Graph {
  constructor() {
    super();
    this.directed = true;
  }
}
```

Then, `Graph` implies an undirected graph, and `DirectedGraph` can be used for initializing a directed graph. Since they both are the same type `Graph`, they can be used anywhere just as usual.

What do you think? This way, we can keep the constructors clean of any parameters.

**Comment by Vijay-Siva** [comment]
I was actually thinking the same thing when I was going over everything today, but I was also trying to plan out how I was going to deal with weighted graphs and unweighted graphs. I'm debating whether I should also make a separate subclass for weighted graphs as well, so in total I will have 4 classes, Graph, WeightedGraph, DirectedGraph, and WeightedDirectedGraph. I wanted to outline and consider all the options before deciding on what to do, but I'm currently leaning towards just making a Graph class and a DirectedGraph class like you said, and then just make the weighted edges, part of the add edge functions as an optional parameter. 

Another thing I need to consider is the graph I need for the flow network class. Graphs in a flow network are unique because each edge is directed, and it has two attributes, a flow and a capacity. So for flow network I would also need another subclass of the Graph class to handle the extra attributes. 

What do you think is the best option, also taking into account the flow network class?

**Comment by qasim** [comment]
I like your idea of having a `Graph` and `DirectedGraph`, and then we could have just an `Edge` with a default weight of something like `1`, but we can do `new Edge(100)` to change the default weight.

For `FlowNetwork`, it could get tricky since then you need 2 types of edges. Maybe you could just focus and only implement `DirectedGraph` and `Edge` with respect to flow networks, and not account for the simpler cases of undirected graphs or regular edges.
