### ISSUE TITLE
Initializing a `Graph` with a list of edges and vertices?

### ISSUE THREAD

**Issue by isthisnagee** [Vijay-Siva/Flows#3]
Since we generally write `G = (V, E)` for a graph (where `V`, `E` are usually predefined), I think it would be pretty useful to be able to initialize a `Graph` in a similar manner, if only to prevent cluttering user code with something like this

```javascript
let G = new Graph()
for (let i = 0; i < Edges.length; i++) {
  G.addEdge(Edges[i])
}
for (let i = 0; i < Vertices.length; i++) {
  G.addVertex(Vertices[i])
}
```
or this.
```javascript
let G = new Graph();
Edges.forEach(e => G.addEdge(e));
Vertices.forEach(v => G.addVertex(e));
```

I'm proposing maybe something like this?

```javascript
let G = new Graph({
  edges: E,
  vertices: V
});
```

So Graphs are initialized with an `options` object (`new Graph(options)`), where `options` include
`directed` (boolean), `edges` (list), and `vertices` (list). 

Thoughts?

**Comment by Vijay-Siva** [comment]
This was something that I considered but I would prefer just sticking to the simplest constructor where a user can simple initialize the graph they want and then create and add vertices and edges later. I think it is simpler, and allows me to encapsulate the class better because the user doesn't need access to the Vertex and Edge class. 

And for directed graphs, I plan on making that a separate subclass. This makes it a lot easier for the user to make exactly what they want without getting confused about all the constructor options. I think separating the different options in different classes makes it easier for the user to learn how to use the API and prevents any accidental dependencies from coming up later.
